Game.exe:main.o  input.o init.o draw.o player.o
	gcc main.o  input.o init.o draw.o player.o collision.c -o Menu.exe -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -g


