Game.exe:main.o structs.o input.o init.o draw.o
	gcc main.o structs.o input.o init.o draw.o -o Menu.exe -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -g

